# Generated by Django 4.2.6 on 2026-04-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orginvite",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orginvite",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="organization.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_orgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="orgmembership",
            constraint=models.UniqueConstraint(
                fields=("user", "org"), name="unique_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="orginvite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("org", "email"),
                name="unique_pending_invite",
            ),
        ),
    ]
