# Generated by Django 4.2.6 on 2026-04-30 08:26

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organisation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("created_by"),
                name="unique_org_per_user_case_insensitive",
            ),
        ),
    ]
