# Generated by Django 4.2.6 on 2026-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_organisation_unique_org_per_user_case_insensitive"),
    ]

    operations = [
        migrations.AddField(
            model_name="orginvite",
            name="role",
            field=models.CharField(
                choices=[("owner", "owner"), ("admin", "Admin"), ("member", "Member")],
                default="member",
                max_length=50,
            ),
        ),
    ]
