# Generated by Django 4.2.6 on 2026-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_orginvite_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
