# Generated by Django 4.2.6 on 2026-10-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_orginvite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_at']},
        ),
    ]
