# Generated by Django 4.2.6 on 2026-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_organisation_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orginvite',
            index=models.Index(fields=['org', 'status'], name='organizatio_org_id_325a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='orginvite',
            index=models.Index(fields=['token', 'status'], name='organizatio_token_23c9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmembership',
            index=models.Index(fields=['org', 'role'], name='organizatio_org_id_651db6_idx'),
        ),
        migrations.AddIndex(
            model_name='orgmembership',
            index=models.Index(fields=['user', 'org'], name='organizatio_user_id_465add_idx'),
        ),
    ]
