# Generated by Django 4.2.6 on 2026-04-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("knowledge_base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebase",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kbs",
                to="organization.organisation",
            ),
        ),
        migrations.AddField(
            model_name="kbdocument",
            name="kb",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="knowledge_base.knowledgebase",
            ),
        ),
    ]
