# Generated by Django 4.2.6 on 2026-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="knowledgebase",
            constraint=models.UniqueConstraint(
                fields=("org", "name"), name="unique_kb_name_per_org"
            ),
        ),
    ]
