# Generated by Django 4.2.6 on 2026-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_knowledgebase_unique_kb_name_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
