# Generated by Django 4.2.6 on 2026-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_knowledgebase_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='kbdocument',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='kbdocument',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kbdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
