# Generated by Django 4.2.6 on 2026-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0005_alter_knowledgebase_options_kbdocument_error_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kbdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='kbdocument',
            index=models.Index(fields=['kb', 'status'], name='knowledge_b_kb_id_3e23dd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['org', '-created_at'], name='knowledge_b_org_id_e787c5_idx'),
        ),
    ]
