# Generated by Django 4.2.6 on 2026-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge_base", "0002_initial"),
        ("chat_bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="kbs",
        ),
        migrations.AddField(
            model_name="bot",
            name="kbs",
            field=models.ManyToManyField(
                blank=True, related_name="bots", to="knowledge_base.knowledgebase"
            ),
        ),
    ]
