# Generated by Django 4.2.6 on 2026-05-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_remove_bot_kbs_bot_kbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful assistant. Answer only using the provided context.'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='botapikey',
            name='name',
            field=models.CharField(default='default', max_length=80),
        ),
        migrations.AlterField(
            model_name='botusage',
            name='api_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='chat_bot.botapikey'),
        ),
    ]
