# Generated by Django 4.2.6 on 2026-09-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_bot_system_prompt_alter_bot_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='allowed_domains',
            field=models.JSONField(default=list),
        ),
    ]
