# Generated by Django 4.2.6 on 2026-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0004_bot_allowed_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['org', 'is_active', '-created_at'], name='chat_bot_bo_org_id_74bbe9_idx'),
        ),
        migrations.AddIndex(
            model_name='botapikey',
            index=models.Index(fields=['bot', 'is_active'], name='chat_bot_bo_bot_id_d9db60_idx'),
        ),
    ]
